In [4]:
# Q1 Create an array
# 10 20 30 40 50
# Print it.
import numpy as np 


In [5]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [9]:
# Q2 Print
# First element
# Last element
# Third element
print(arr[0])
print(arr[-1])
print(arr[2])


10
50
30


In [12]:
# Q3
# Print
# 20 30 40
# using slicing.
print(arr[1:4])

[20 30 40]


In [14]:
# Q4
# Print
# ndim
# shape
# size
# dtype
print(arr.ndim)
print(arr.shape)

1
(5,)


In [16]:
print(arr.size)

5


In [17]:
print(arr.dtype)

int64


In [18]:
# Q5
# Create
# [5,10,15,20,25]
# Print every element using a loop.
a = np.array([5,10,15,20,25])
print(a)

[ 5 10 15 20 25]


In [35]:
for i in a:
    print(i)

5
10
15
20
25


In [32]:
# Student Marks Analyzer
# Create
# marks = np.array([78,85,91,67,88])
# Print:
# Highest mark
# Lowest mark
# Average mark
marks = np.array([78,85,91,67,88])
print("Max marks are",np.max(marks))

Max marks are 91


In [33]:
print("Min marks are",np.min(marks))

Min marks are 67


In [34]:
print("Average marks are",np.average(marks))

Average marks are 81.8


In [29]:
print(np.min(marks))

67
