In [3]:
import numpy as np 
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [4]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [6]:
arr = np.zeros((3,4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [8]:
arr = np.full(5,10)
print(arr)

[10 10 10 10 10]


In [9]:
arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [12]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [15]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr[1,2])

6


In [18]:
arr = np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [19]:
print(arr[:3])

[10 20 30]


In [21]:
print(arr[2:])

[30 40 50]


In [23]:
print(arr[::2])

[10 30 50]


In [24]:
print(arr[::-1])

[50 40 30 20 10]


In [25]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[:2])

[[1 2 3]
 [4 5 6]]


In [26]:
print(arr[:,1])

[2 5 8]


In [27]:
print(arr[1,1])

5


In [28]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]
