In [1]:
import numpy as np 
arr = np.array([10,20,30])
print(arr.ndim)

1


In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [3]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(arr.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [4]:
print(arr.shape)


(2, 2, 2)


In [5]:
print(arr.size)

8


In [6]:
print(arr.dtype)

int64


In [8]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(3,2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
print(new_arr.flatten())

[1 2 3 4 5 6]


In [10]:
print(new_arr.T)

[[1 3 5]
 [2 4 6]]


In [11]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [13]:
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]
