In [1]:
import numpy as np

In [2]:
c = np.array([1,2,3])
d = np.array([2,4,5])

In [3]:
c + d


array([3, 6, 8])

In [4]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[2,3,4],[3,4,6]])

In [5]:
a * b

array([[ 2,  6, 12],
       [ 6, 12, 24]])

In [6]:
a + b


array([[ 3,  5,  7],
       [ 5,  7, 10]])

In [7]:
a - b

array([[-1, -1, -1],
       [-1, -1, -2]])

In [9]:

np.dot(a,np.transpose(b))


array([[20, 29],
       [29, 42]])